export const offendersSet1: { surname: string, forename: string }[] = [
    { surname: 'NOD1047-1-01', forename: 'Offender' },
    { surname: 'NOD1047-1-02', forename: 'Offender' },
    { surname: 'NOD1047-1-03', forename: 'Offender' },
    { surname: 'NOD1047-1-04', forename: 'Offender' },
    { surname: 'NOD1047-1-05', forename: 'Offender' },
    { surname: 'NOD1047-1-06', forename: 'Offender' },
    { surname: 'StreamliningOneSeven', forename: 'Offender' },
    { surname: 'NOD1047-1-08', forename: 'Offender' },
    { surname: 'NOD1047-1-09', forename: 'Offender' },
    { surname: 'NOD1047-1-10', forename: 'Offender' },
    { surname: 'NOD1047-1-11', forename: 'Offender' },
    { surname: 'NOD1047-1-12', forename: 'Offender' },
    { surname: 'NOD1047-1-13', forename: 'Offender' },
    { surname: 'StreamliningOneFourteen', forename: 'Offender' },
]

export const offendersSet2: { surname: string, forename: string }[] = [
    { surname: 'NOD1047-2-01', forename: 'Offender' },
    { surname: 'NOD1047-2-02', forename: 'Offender' },
    { surname: 'NOD1047-2-03', forename: 'Offender' },
    { surname: 'NOD1047-2-04', forename: 'Offender' },
    { surname: 'NOD1047-2-05', forename: 'Offender' },
    { surname: 'NOD1047-2-06', forename: 'Offender' },
    { surname: 'StreamliningTwoSeven', forename: 'Offender' },
    { surname: 'NOD1047-2-08', forename: 'Offender' },
    { surname: 'NOD1047-2-09', forename: 'Offender' },
    { surname: 'NOD1047-2-10', forename: 'Offender' },
    { surname: 'NOD1047-2-11', forename: 'Offender' },
    { surname: 'NOD1047-2-12', forename: 'Offender' },
    { surname: 'NOD1047-2-13', forename: 'Offender' },
    { surname: 'StreamliningTwoFourteen', forename: 'Offender' },
]
