// import * as oasys from 'oasys'
// import { sets, getSurname } from '../parameters'

// describe('NOD1045 prison non-SAN completed assessments', () => {

//     it('Test ref 17', () => { // MALE Offender whose last assessment is a COMPLETED L3 V1 Start Custody with Initial SP.

//         oasys.login(oasys.Users.prisHomds)

//         for (let set = 1; set <= sets; set++) {

//             oasys.Offender.searchAndSelectByName(getSurname(set), 'TestRef17')
//             oasys.Assessment.createPris({ purposeOfAssessment: 'Start custody', assessmentLayer: 'Full (Layer 3)' })

//             oasys.Populate.CommonPages.OffendingInformation.minimal()

//             const predictors = new oasys.Pages.Assessment.Predictors().goto(true)
//             predictors.dateFirstSanction.setValue({ years: -3 })
//             predictors.o1_32.setValue(2)
//             predictors.o1_40.setValue(0)
//             predictors.o1_29.setValue({ months: -6 })
//             predictors.o1_44.setValue('Yes')
//             predictors.o1_33.setValue({ months: -6 })
//             predictors.o1_34.setValue(1)
//             predictors.o1_45.setValue(1)
//             predictors.o1_46.setValue(1)
//             predictors.o1_38.setValue({ months: -1 })
//             predictors.o1_37.setValue(1)

//             oasys.Populate.sections2To13NoIssues()
//             oasys.Populate.CommonPages.SelfAssessmentForm.minimal()

//             const section3 = new oasys.Pages.Assessment.Section3().goto()
//             section3.o3_3.setValue('Yes')
//             section3.linkedToRisk.setValue('Yes')
//             oasys.Nav.clickButton('Save')   // to handle notification of changed scores

//             oasys.Populate.RoshPages.RoshScreeningSection1.noRisks()

//             const risk2 = new oasys.Pages.Rosh.RoshScreeningSection2to4().goto()
//             risk2.r2_3.setValue('Yes')
//             risk2.r2_4_1.setValue('Yes')
//             risk2.r2_4_2.setValue('No')
//             risk2.r3_1.setValue('Yes')
//             risk2.r3_2.setValue('Yes')
//             risk2.r3_3.setValue('Yes')
//             risk2.r3_4.setValue('Yes')
//             risk2.r4_1.setValue('Yes')
//             risk2.r4_2.setValue('Yes')
//             risk2.r4_3.setValue('Yes')
//             risk2.r4_4.setValue('No')

//             const child = new oasys.Pages.Rosh.ChildAtRisk().goto(true)
//             child.childName.setValue('Child 1')
//             child.dateOfBirth.setValue({ years: -5 })
//             child.gender.setValue('Male')
//             child.address.setValue('The home address')
//             child.relationship.setValue('Other')
//             child.relationshipOther.setValue('Some other relationship')
//             child.contact.setValue('Yes')
//             child.save.click()
//             child.close.click()

//             const risk61 = new oasys.Pages.Rosh.RoshFullAnalysisSection61().goto(true)
//             risk61.what.setValue('6.1 What ' + oasys.oasysString(2991))
//             risk61.whereAndWhen.setValue('6.1 WhereAndWhen ' + oasys.oasysString(2983))
//             risk61.how.setValue('6.1 How ' + oasys.oasysString(2992))
//             risk61.victims.setValue('6.1 Victims ' + oasys.oasysString(2988))
//             risk61.anyoneElse.setValue('6.1 AnyoneElse ' + oasys.oasysString(2985))
//             risk61.why.setValue('6.1 Why ' + oasys.oasysString(2991))
//             risk61.sourcesOfInformation.setValue('6.1 SourcesOfInformation ' + oasys.oasysString(2975))

//             const risk62 = new oasys.Pages.Rosh.RoshFullAnalysisSection62().goto(true)
//             risk62.what.setValue('6.2  What ' + oasys.oasysString(2991))
//             risk62.whereAndWhen.setValue('6.2  WhereAndWhen ' + oasys.oasysString(2983))
//             risk62.how.setValue('6.2  How ' + oasys.oasysString(2992))
//             risk62.victims.setValue('6.2  Victims ' + oasys.oasysString(2988))
//             risk62.anyoneElse.setValue('6.2  AnyoneElse ' + oasys.oasysString(2985))
//             risk62.why.setValue('6.2  Why ' + oasys.oasysString(2991))
//             risk62.sourcesOfInformation.setValue('6.2 SourcesOfInformation ' + oasys.oasysString(2975))

//             new oasys.Pages.Rosh.RoshFullAnalysisSection7().goto()
//             cy.get('a').contains('Child 1').click()
//             child.worried.setValue('No')
//             child.knownToServices.setValue('No')
//             child.save.click()
//             child.close.click()

//             const risk8 = new oasys.Pages.Rosh.RoshFullAnalysisSection8().goto(true)
//             risk8.concernsSuicide.setValue('Yes')
//             risk8.concernsSelfHarm.setValue('Yes')
//             risk8.suicideHarmDetails.setValue('SuicideHarmDetails ' + oasys.oasysString(2981))
//             risk8.acct.setValue('Yes')
//             risk8.bookNumber.setValue('BookNumber')
//             risk8.concernsSuicidePast.setValue('Yes')
//             risk8.concernsSelfHarmPast.setValue('Yes')
//             risk8.suicideHarmDetailsPast.setValue('SuicideHarmDetailsPast ' + oasys.oasysString(2977))
//             risk8.concernsCustody.setValue('Yes')
//             risk8.concernsHostel.setValue('Yes')
//             risk8.custodyHostelDetails.setValue('CustodyHostelDetails ' + oasys.oasysString(2979))
//             risk8.concernsCustodyPrevious.setValue('Yes')
//             risk8.concernsHostelPrevious.setValue('Yes')
//             risk8.custodyHostelDetailsPrevious.setValue('CustodyHostelDetailsPrevious ' + oasys.oasysString(2971))
//             risk8.concernsVulnerability.setValue('Yes')
//             risk8.vulnerabilityDetails.setValue('VulnerabilityDetails ' + oasys.oasysString(2979))
//             risk8.concernsVulnerabilityPrevious.setValue('Yes')
//             risk8.vulnerabilityDetailsPrevious.setValue('VulnerabilityDetailsPrevious ' + oasys.oasysString(2979))
//             risk8.roshOthers.setValue('Yes')
//             risk8.riskDetails.setValue('RiskDetails ' + oasys.oasysString(2988))

//             const risk9 = new oasys.Pages.Rosh.RoshFullAnalysisSection9().goto(true)
//             risk9.concernsEscape.setValue('Yes')
//             risk9.concernsEscapeDetails.setValue('ConcernsEscapeDetails ' + oasys.oasysString(2978))
//             risk9.concernsEscapePrevious.setValue('Yes')
//             risk9.concernsEscapePreviousDetails.setValue('ConcernsEscapePreviousDetails ' + oasys.oasysString(2970))
//             risk9.concernsControl.setValue('Yes')
//             risk9.concernsControlDetails.setValue('ConcernsControlDetails ' + oasys.oasysString(2977))
//             risk9.concernsControlPrevious.setValue('Yes')
//             risk9.concernsControlPreviousDetails.setValue('ConcernsControlPreviousDetails ' + oasys.oasysString(2969))
//             risk9.concernsTrust.setValue('Yes')
//             risk9.concernsTrustDetails.setValue('ConcernsTrustDetails ' + oasys.oasysString(2979))
//             risk9.concernsTrustPrevious.setValue('Yes')
//             risk9.concernsTrustPreviousDetails.setValue('ConcernsTrustPreviousDetails ' + oasys.oasysString(2971))

//             const roshSummary = new oasys.Pages.Rosh.RoshSummary().goto(true)
//             roshSummary.r10_1.setValue('R10.1 details ' + oasys.oasysString(2986))
//             roshSummary.r10_2.setValue('R10.2 details ' + oasys.oasysString(2986))
//             roshSummary.r10_3.setValue('R10.3 details ' + oasys.oasysString(2986))
//             roshSummary.r10_4.setValue('R10.4 details ' + oasys.oasysString(2986))
//             roshSummary.r10_5.setValue('R10.5 details ' + oasys.oasysString(2986))
//             roshSummary.r10_6ChildrenCommunity.setValue('High')
//             roshSummary.r10_6ChildrenCustody.setValue('Medium')
//             roshSummary.r10_6PublicCommunity.setValue('Medium')
//             roshSummary.r10_6PublicCustody.setValue('Medium')
//             roshSummary.r10_6AdultCommunity.setValue('Medium')
//             roshSummary.r10_6AdultCustody.setValue('Medium')
//             roshSummary.r10_6StaffCommunity.setValue('Medium')
//             roshSummary.r10_6StaffCustody.setValue('Medium')
//             roshSummary.r10_6PrisonersCustody.setValue('Medium')
//             roshSummary.details.setValue('Some details about documents and reports ' + oasys.oasysString(2959))

//             oasys.Populate.RoshPages.RiskManagementPlan.minimalWithTextFields(true)

//             oasys.Populate.SentencePlanPages.IspSection1to4.fullyPopulated()
//             oasys.Populate.SentencePlanPages.IspSection5.fullyPopulated()
//             oasys.Populate.SentencePlanPages.IspSection52to8.fullyPopulated()
//             oasys.Assessment.signAndLock()
//         }
//     })

// })
