import { Page } from 'classes/page'
import * as Element from 'classes/elements'

export class ObjectivesAndActions extends Page {

    name = 'ObjectivesAndActions'
    title = 'Objectives and Actions'
    menu: Menu = { type: 'Subform', level1: 'Add Objective' }

    save = new Element.Button('Save')
    close = new Element.Button('Close')
    clearPlan = new Element.Button('Clear Plan')
    futureObjective = new Element.Checkbox('#P4_FUTURE_OBJECTIVE_0')
    objectiveCategory = new Element.Select('#P4_OBJECTIVE_CAT')
    objective = new Element.Select('#P4_OBJECTIVE_CODE')
    description = new Element.Textbox('#P4_OBJECTIVE_DESC')
    relevantOasysItem1 = new Element.Select('#P4_CRIMINOGENIC_NEED_1')
    relevantOasysItem2 = new Element.Select('#P4_CRIMINOGENIC_NEED_2')
    relevantOasysItem3 = new Element.Select('#P4_CRIMINOGENIC_NEED_3')
    relevantOasysItem4 = new Element.Select('#P4_CRIMINOGENIC_NEED_4')
    measureProgress = new Element.Textbox('#P4_PROGRESS_MEASURED')
    objectiveStatus = new Element.Select<ObjectiveStatus>('#P4_OBJECTIVE_STATUS')
    objectiveStatusComments = new Element.Textbox('#P4_OBJ_STATUS_COMMENTS')
    action1 = new Element.Link("a[accesskey='1']")
    action2 = new Element.Link("a[accesskey='2']")
    action3 = new Element.Link("a[accesskey='3']")
    historicActions = new Element.Link('Historic Actions')
    useExisting = new Element.Button('Use Existing')
    remove = new Element.Button('Remove')
    action = new Element.Select('#P4_ACTION')
    actionDescription = new Element.Textbox('#P4_ACTION_DESC')
    who1 = new Element.Select('#P4_WHO_WILL_DO_WORK1')
    whoComments1 = new Element.Textbox('#P4_WWDW_COMMENTS1')
    who2 = new Element.Select('#P4_WHO_WILL_DO_WORK2')
    whoComments2 = new Element.Textbox('#P4_WWDW_COMMENTS2')
    who3 = new Element.Select('#P4_WHO_WILL_DO_WORK3')
    whoComments3 = new Element.Textbox('#P4_WWDW_COMMENTS3')
    timescale = new Element.Select('#P4_TIMESCALE')
    actionStatus = new Element.Select<ActionStatus>('#P4_ACTION_STATUS')
    actionStatusComments = new Element.Textbox('#P4_ACTION_STATUS_COMMENTS')
    action_2 = new Element.Select('#P4_ACTION_2')
    actionDescription_2 = new Element.Textbox('#P4_ACTION_DESC_2')
    who1_2 = new Element.Select('#P4_WHO_WILL_DO_WORK1_2')
    whoComments1_2 = new Element.Textbox('#P4_WWDW_COMMENTS1_2')
    who2_2 = new Element.Select('#P4_WHO_WILL_DO_WORK2_2')
    whoComments2_2 = new Element.Textbox('#P4_WWDW_COMMENTS2_2')
    who3_2 = new Element.Select('#P4_WHO_WILL_DO_WORK3_2')
    whoComments3_2 = new Element.Textbox('#P4_WWDW_COMMENTS3_2')
    timescale_2 = new Element.Select('#P4_TIMESCALE_2')
    actionStatus_2 = new Element.Select('#P4_ACTION_STATUS_2')
    actionStatusComments_2 = new Element.Textbox('#P4_ACTION_STATUS_COMMENTS_2')
    action_3 = new Element.Select('#P4_ACTION_3')
    actionDescription_3 = new Element.Textbox('#P4_ACTION_DESC_3')
    who1_3 = new Element.Select('#P4_WHO_WILL_DO_WORK1_3')
    whoComments1_3 = new Element.Textbox('#P4_WWDW_COMMENTS1_3')
    who2_3 = new Element.Select('#P4_WHO_WILL_DO_WORK2_3')
    whoComments2_3 = new Element.Textbox('#P4_WWDW_COMMENTS2_3')
    who3_3 = new Element.Select('#P4_WHO_WILL_DO_WORK3_3')
    whoComments3_3 = new Element.Textbox('#P4_WWDW_COMMENTS3_3')
    timescale_3 = new Element.Select('#P4_TIMESCALE_3')
    actionStatus_3 = new Element.Select('#P4_ACTION_STATUS_3')
    actionStatusComments_3 = new Element.Textbox('#P4_ACTION_STATUS_COMMENTS_3')
    actionColumn = new Element.Column(Element.ColumnType.Column, 'Action')
    timescaleColumn = new Element.Column(Element.ColumnType.Column, 'Timescale')
    statusColumn = new Element.Column(Element.ColumnType.Column, 'Status')
    statusCommentColumn = new Element.Column(Element.ColumnType.Column, 'Status Comment')
    endDateColumn = new Element.Column(Element.ColumnType.Column, 'End Date')
}
