import { Page } from 'classes/page'
import * as Element from 'classes/elements'

export class MaintainCmsStub extends Page {

    name = 'MaintainCmsStub'
    title = 'Testr Mode - CMS Stub'

    close = new Element.Button('Close')
    save = new Element.Button('Save')
    receptionEvent = new Element.Button('Reception Event')
    releaseEvent = new Element.Button('Release Event')
    prisonNumber = new Element.Textbox('#P100_PRISON_NUMBER')
    nomisId = new Element.Textbox('#P100_CMS_PRIS_NUMBER')
    probationCrn = new Element.Textbox('#P100_CMS_PROB_NUMBER')
    cro = new Element.Textbox('#P100_CRONUMBER')
    pnc = new Element.Textbox('#P100_PNC')
    surname = new Element.Textbox('#P100_FAMILY_NAME')
    forename1 = new Element.Textbox('#P100_FORENAME_1')
    forename2 = new Element.Textbox('#P100_FORENAME_2')
    forename3 = new Element.Textbox('#P100_FORENAME_3')
    gender = new Element.Select('#P100_GENDER_ELM')
    ethnicity = new Element.Select('#P100_ETHNIC_CATEGORY_ELM')
    dateOfBirth = new Element.Textbox<OasysDate>('#P100_DATE_OF_BIRTH')
    limitedAccessOffender = new Element.Checkbox('#P100_LAO_INDICATOR_0')
    language = new Element.Select('#P100_LANGUAGE_ELM')
    phoneNumber = new Element.Textbox('#P100_TELEPHONE_NUMBER')
    religion = new Element.Select('#P100_RELIGION_ELM')
    addressLine1 = new Element.Textbox('#P100_ADDRESS_LINE_1')
    addressLine2 = new Element.Textbox('#P100_ADDRESS_LINE_2')
    addressLine3 = new Element.Textbox('#P100_ADDRESS_LINE_3')
    addressLine4 = new Element.Textbox('#P100_ADDRESS_LINE_4')
    addressLine5 = new Element.Textbox('#P100_ADDRESS_LINE_5')
    addressLine6 = new Element.Textbox('#P100_ADDRESS_LINE_6')
    postcode = new Element.Textbox('#P100_ADDRESS_POSTCODE')
    cellLocation = new Element.Textbox('#P100_CELL_LOCATION')
    securityCategory = new Element.Textbox('#P100_SECURITY_CATEGORY')
    receptionCode = new Element.Select('#P100_RECEPTION_CODE_ELM')
    dischargeCode = new Element.Select('#P100_DISCHARGE_CODE_ELM')
    dischargeAddressLine1 = new Element.Textbox('#P100_DISCHARGE_ADDRESS_LINE_1')
    dischargeAddressLine2 = new Element.Textbox('#P100_DISCHARGE_ADDRESS_LINE_2')
    dischargeAddressLine3 = new Element.Textbox('#P100_DISCHARGE_ADDRESS_LINE_3')
    dischargeAddressLine4 = new Element.Textbox('#P100_DISCHARGE_ADDRESS_LINE_4')
    dischargeAddressLine5 = new Element.Textbox('#P100_DISCHARGE_ADDRESS_LINE_5')
    dischargePostcode = new Element.Textbox('#P100_DISCHARGE_POSTCODE')
    dischargeTelephoneNumber = new Element.Textbox('#P100_DISCHARGE_TELEPHONE_NUM')
    appealPending = new Element.Checkbox('#P100_APPEALANT_IND')
    homeDetentionCurfewDate = new Element.Textbox<OasysDate>('#P100_CURFEW_DATE')
    paroleEligibilityDate = new Element.Textbox<OasysDate>('#P100_PAROLE_ELIGIBILITY_DATE')
    nonParoleDate = new Element.Textbox<OasysDate>('#P100_NON_PAROLE_DATE')
    licenceExpiryDate = new Element.Textbox<OasysDate>('#P100_LICENCE_EXPIRY_DATE')
    automaticReleaseDate = new Element.Textbox<OasysDate>('#P100_AUTOMATIC_RELEASE_DATE')
    conditionalReleaseDate = new Element.Textbox<OasysDate>('#P100_CONDITIONAL_RELEASE_DATE')
    sentenceExpiryDate = new Element.Textbox<OasysDate>('#P100_SENTENCE_EXPIRY_DATE')
    riskOfSelfHarm = new Element.Checkbox('#P100_RISK_OF_SELF_HARM_0')
    event = new Element.Link('#current')
    createEvent = new Element.Button('Create')
    sentenceTypeColumn = new Element.Column(Element.ColumnType.Column, 'Sentence Type')
    eventNumberColumn = new Element.Column(Element.ColumnType.Column, 'Event Number')
    sentenceDateColumn = new Element.Column(Element.ColumnType.Column, 'Sentence Date')
    releaseDateColumn = new Element.Column(Element.ColumnType.Column, 'Release Date')
    offenderAlias = new Element.Link('Offender Alias')
    createAlias = new Element.Button('Create')
    aliasSurnameColumn = new Element.Column(Element.ColumnType.Column, 'Surname')
    aliasDateOfBirthColumn = new Element.Column(Element.ColumnType.Column, 'Date of Birth')
    aliasDeleteColumn = new Element.Column(Element.ColumnType.ButtonColumn, '')
}
