import * as oasys from 'oasys'

export function fullyPopulatedChild1(maxStrings: boolean = false) {

    const page = new oasys.Pages.Rosh.ChildAtRisk().goto(true)
    page.childName.setValue(maxStrings ? oasys.oasysString(96) : 'Child 1')
    page.dateOfBirth.setValue({ years: -5 })
    page.gender.setValue('Male')
    page.address.setValue(maxStrings ? oasys.oasysString(256) : 'The home address')
    page.relationship.setValue('Other')
    page.relationshipOther.setValue(maxStrings ? oasys.oasysString(100) : 'Some other relationship')
    page.contact.setValue('Yes')
    page.worried.setValue('Yes')
    page.worriedAbout.setValue(maxStrings ? oasys.oasysString(4000) : 'Loads of worrying stuff')
    page.knownToServices.setValue('Yes')
    page.earlyHelpCurrent.setValue(true)
    page.earlyHelpPrevious.setValue(true)
    page.childInNeedCurrent.setValue(true)
    page.childInNeedPrevious.setValue(true)
    page.cppCurrent.setValue(true)
    page.cppPrevious.setValue(true)
    page.currentNeglect.setValue(true)
    page.currentPhysical.setValue(true)
    page.currentSexual.setValue(true)
    page.currentEmotional.setValue(true)
    page.previousNeglect.setValue(true)
    page.previousPhysical.setValue(true)
    page.previousSexual.setValue(true)
    page.previousEmotional.setValue(true)
    page.briefDetails.setValue(maxStrings ? oasys.oasysString(500) : 'Some brief details')
    page.shareWithServices.setValue('No')
    page.recordRationale.setValue(maxStrings ? oasys.oasysString(200) : 'There must be a reason')
    page.save.click()
    page.close.click()
}

export function fullyPopulatedChild2(maxStrings: boolean = false) {

    const page = new oasys.Pages.Rosh.ChildAtRisk().goto(true)
    page.childName.setValue(maxStrings ? oasys.oasysString(96) : 'Child 2')
    page.age.setValue('8')
    page.gender.setValue('Female')
    page.address.setValue(maxStrings ? oasys.oasysString(256) : 'Somewhere else')
    page.relationship.setValue('Carer')
    page.contact.setValue('Yes')
    page.worried.setValue('Yes')
    page.worriedAbout.setValue(maxStrings ? oasys.oasysString(4000) : 'More worrying stuff')
    page.knownToServices.setValue('Yes')
    page.earlyHelpCurrent.setValue(true)
    page.earlyHelpPrevious.setValue(false)
    page.childInNeedCurrent.setValue(true)
    page.childInNeedPrevious.setValue(false)
    page.cppCurrent.setValue(false)
    page.cppPrevious.setValue(true)
    page.currentNeglect.setValue(false)
    page.currentPhysical.setValue(true)
    page.currentSexual.setValue(true)
    page.currentEmotional.setValue(false)
    page.previousNeglect.setValue(true)
    page.previousPhysical.setValue(false)
    page.previousSexual.setValue(false)
    page.previousEmotional.setValue(true)
    page.briefDetails.setValue(maxStrings ? oasys.oasysString(500) : 'Some more brief details')
    page.shareWithServices.setValue('Yes')
    page.save.click()
    page.close.click()
}
