import { Page } from 'classes/page'
import * as Element from 'classes/elements'

export class CmsOffenderDetails extends Page {

    name = 'CmsOffenderDetails'
    title = 'CMS Offender Details'

    close = new Element.Button('Close')
    cmsProbationCrn = new Element.Textbox('#P100_PROB_CRN')
    cmsFamilyName = new Element.Textbox('#P100_SURNAME')
    cmsForename1 = new Element.Textbox('#P100_FORENAME_1')
    cmsForename2 = new Element.Textbox('#P100_FORENAME_2')
    cmsForename3 = new Element.Textbox('#P100_FORENAME_3')
    cmsGender = new Element.Textbox('#P100_GENDER')
    cmsDateOfBirth = new Element.Textbox<OasysDate>('#P100_DATE_OF_BIRTH')
    cmsEthnicity = new Element.Textbox('#P100_ETHNICITY')
    cmsAddressLine1 = new Element.Textbox('#P100_ADDRESS_LINE_1')
    cmsAddressLine2 = new Element.Textbox('#P100_ADDRESS_LINE_2')
    cmsAddressLine3 = new Element.Textbox('#P100_ADDRESS_LINE_3')
    cmsAddressLine4 = new Element.Textbox('#P100_ADDRESS_LINE_4')
    cmsAddressLine5 = new Element.Textbox('#P100_ADDRESS_LINE_5')
    cmsAddressLine6 = new Element.Textbox('#P100_ADDRESS_LINE_6')
    cmsPostCode = new Element.Textbox('#P100_POSTCODE')
    cmsTelephoneNumber = new Element.Textbox('#P100_TELEPHONE_NO')
    cmsPreferredLanguage = new Element.Textbox('#P100_LANGUAGE_ELM')
    cmsReligion = new Element.Textbox('#P100_RELIGION_ELM')
    cmsPncNumber = new Element.Textbox('#P100_PNC')
    cmsCroNumber = new Element.Textbox('#P100_CRO')
    cmsPrisonLidsNumber = new Element.Textbox('#P100_LIDS')
    cmsPrisonNomisNumber = new Element.Textbox('#P100_LIDS')
    cmsShowAliases = new Element.Button('Show Aliases')
    oasysProbationCrn = new Element.Textbox('#P100_PROB_CRN_O')
    oasysFamilyName = new Element.Textbox('#P100_SURNAME_O')
    oasysForename1 = new Element.Textbox('#P100_FORENAME_1_O')
    oasysForename2 = new Element.Textbox('#P100_FORENAME_2_O')
    oasysForename3 = new Element.Textbox('#P100_FORENAME_3_O')
    oasysGender = new Element.Textbox('#P100_GENDER_O')
    oasysDateOfBirth = new Element.Textbox<OasysDate>('#P100_DATE_OF_BIRTH_O')
    oasysEthnicity = new Element.Textbox('#P100_ETHNICITY_O')
    oasysAddressLine1 = new Element.Textbox('#P100_ADDRESS_LINE_1_O')
    oasysAddressLine2 = new Element.Textbox('#P100_ADDRESS_LINE_2_O')
    oasysAddressLine3 = new Element.Textbox('#P100_ADDRESS_LINE_3_O')
    oasysAddressLine4 = new Element.Textbox('#P100_ADDRESS_LINE_4_O')
    oasysAddressLine5 = new Element.Textbox('#P100_ADDRESS_LINE_5_O')
    oasysAddressLine6 = new Element.Textbox('#P100_ADDRESS_LINE_6_O')
    oasysPostCode = new Element.Textbox('#P100_POSTCODE_O')
    oasysTelephoneNumber = new Element.Textbox('#P100_TELEPHONE_NO_O')
    oasysPreferredLanguage = new Element.Textbox('#P100_LANGUAGE_ELM_O')
    oasysReligion = new Element.Textbox('#P100_RELIGION_ELM_O')
    oasysPncNumber = new Element.Textbox('#P100_PNC_O')
    oasysCroNumber = new Element.Textbox('#P100_CRO_O')
    oasysPrisonLidsNumber = new Element.Textbox('#P100_LIDS_O')
    oasysPrisonNomisNumber = new Element.Textbox('#P100_LIDS_O')
    oasysShowAliases = new Element.Button('Show Aliases_O')
    offenceDesc = new Element.Textbox('#P100_OFFENCE_DESC')
    subcodeDesc = new Element.Textbox('#P100_SUBCODE_DESC')
    code = new Element.Textbox('#P100_OFFENCE_GROUP_CODE')
    subcode = new Element.Textbox('#P100_SUB_CODE')
    sentenceStartdate = new Element.Textbox<OasysDate>('#P100_SENTENCE_DATE')
    actualReleaseDate = new Element.Textbox<OasysDate>('#P100_RELEASE_DATE')
    sentence = new Element.Textbox('#P100_SENTENCE_CODE')
    custodyRehabMonths = new Element.Textbox('#P100_SENTENCE_LENGTH')
    communityPunishmentHours = new Element.Textbox('#P100_COMBINED_LENGTH')
    additionalRequirement1 = new Element.Textbox('#P100_ADDITIONAL_REQ_1')
    additionalRequirement2 = new Element.Textbox('#P100_ADDITIONAL_REQ_2')
    additionalRequirement3 = new Element.Textbox('#P100_ADDITIONAL_REQ_3')
    licenceCondition = new Element.Textbox('#P100_LICENCE')
    courtName = new Element.Textbox('#P100_COURT_NAME')
    courtCode = new Element.Textbox('#P100_COURT_CODE')
    courtType = new Element.Textbox('#P100_COURT_TYPE_ELM')
    createOffender = new Element.Button('Create Offender')
    updateOffender = new Element.Button('Update Offender')
}

