import * as Element from 'classes/elements'
import { Page } from 'classes/page'

export class OffenderDetails extends Page {

    name = 'OffenderDetails'
    title = 'Offender'

    updateFromDelius = new Element.Button('Update from Delius')
    print = new Element.Button('Print')
    createAssessment = new Element.Button('Create Assessment')
    createBcs = new Element.Button('Create BCS')
    requestTransfer = new Element.Button('Request Transfer')
    requestAutomaticTransfer = new Element.Button('Request Automatic Transfer')
    lao = new Element.Button('LAO')
    rfi = new Element.Button('RFI')
    rsr = new Element.Button('RSR')
    rfa = new Element.Button('RFA')
    demerge = new Element.Button('Demerge')
    unknownPnc = new Element.Button('Unknown PNC')
    openSan = new Element.Button('Open S&N')
    openSp = new Element.Button('Open SP')
    statusIcons = new Element.IconContainer('#P10_ICONS')
    save = new Element.Button('Save')
    close = new Element.Button('Close')
    offenderTitle = new Element.Select('#P10_TITLE_ELM')
    lifer = new Element.Checkbox('#P10_LIFE_IND_0')
    surname = new Element.Textbox('#P10_FAMILY_NAME')
    pnc = new Element.Textbox('#P10_PNC')
    mergePnc = new Element.Textbox('#P10_MERGE_PNC_NUMBER')
    deciderPnc = new Element.Textbox('#P10_DECIDER_PNC')
    forename = new Element.Textbox('#P10_FORENAME_1')
    forename2 = new Element.Textbox('#P10_FORENAME_2')
    cro = new Element.Textbox('#P10_CRO_NUMBER')
    controllingOwner = new Element.Textbox('#P10_PRIMARY_LOC_AREA_DESC')
    forename3 = new Element.Textbox('#P10_FORENAME_3')
    probationCrn = new Element.Textbox('#P10_CMS_PROB_NUMBER')
    providerEstLocation = new Element.Textbox('#P10_PHYSICAL_LOCATION')
    dateOfBirth = new Element.Textbox<OasysDate>('#P10_DATE_OF_BIRTH')
    prisonNomisNo = new Element.Textbox('#P10_CMS_PRIS_NUMBER')
    otherLocation = new Element.Checkbox('#P10_OTHER_LOCATION_IND_0')
    otherLocationText = new Element.Textbox('#P10_PHYSICAL_LOCATION_OTHER')
    gender = new Element.Select('#P10_GENDER_ELM')
    prisonLidsNo = new Element.Textbox('#P10_PRISON_NUMBER')
    deceased = new Element.Checkbox('#P10_DECEASED_IND_0')
    dateOfDeath = new Element.Textbox<OasysDate>('#P10_DATE_OF_DEATH')
    ethnicCategory = new Element.Select('#P10_ETHNIC_CATEGORY_ELM')
    assessmentsTab = new Element.Link('Assessments')
    offenderAddressTab = new Element.Link('Offender Address')
    aliasTab = new Element.Link('Alias')
    offenderManagementTab = new Element.Link('Offender Management')
    summarySheetTab = new Element.Link('Summary Sheet')
    offenderHistoryTab = new Element.Link('Offender History')
    rfiTab = new Element.Link('RFI')
    intbdttoTab = new Element.Link('INTBDTTO')
}
