import { Page } from 'classes/page'
import * as Element from 'classes/elements'
import { BaseAssessmentPage } from '../baseAssessmentPage'

export class OffendingInformation extends BaseAssessmentPage {

    name = 'OffendingInformation'
    title = '1 - Offending Information'
    menu: Menu = { type: 'Floating', level1: 'Section 1', level2: 'Offending Information' }

    markAsComplete = new Element.Button('Mark as Complete')  // override the Base as capitalisation is different
    removeOrder = new Element.Button('Remove Order')
    currentEvent = new Element.Link('Current Event')
    concurrentOrder2 = new Element.Link('Concurrent Order 2')
    concurrentOrder3 = new Element.Link('Concurrent Order 3')
    concurrentOrder4 = new Element.Link('Concurrent Order 4')
    concurrentOrder5 = new Element.Link('Concurrent Order 5')
    offence = new Element.Textbox('#P6_CT_OFFENCE_CODE_TEXT')
    offenceDescription = new Element.Textbox('#LOVDSC_P6_CT_OFFENCE_CODE_TEXT')
    subcode = new Element.Textbox('#P6_CT_OFFENCE_SUBCODE_TEXT')
    subcodeDescription = new Element.Textbox('#LOVDSC_P6_CT_OFFENCE_SUBCODE_TEXT')
    count = new Element.Textbox<number>('#P6_COUNT_OF_OFFENCES')
    offenceDate = new Element.Textbox<OasysDate>('#P6_OFFENCE_DATE')
    offenceLOV = new Element.Link("//input[@id='P6_CT_OFFENCE_CODE_TEXT']/following::a/img")
    subcodeLOV = new Element.Link("//input[@id='P6_CT_OFFENCE_SUBCODE_TEXT']/following::a/img")
    codeColumn = new Element.Column(Element.ColumnType.Column, 'Code')
    subcodeColumn = new Element.Column(Element.ColumnType.Column, 'Subcode')
    descriptionColumn = new Element.Column(Element.ColumnType.Column, 'Description')
    countColumn = new Element.Column(Element.ColumnType.Column, 'Count')
    deleteColumn = new Element.Column(Element.ColumnType.ButtonColumn, 'Delete')
    addAdditionalOffences = new Element.Button('Add Additional Offences')
    resentencingForBreach = new Element.Select('#P6_RESENTENCE_FOR_BREACH_IND')
    orderAmended = new Element.Select('#P6_ORDER_AMENDED')
    dateAmended = new Element.Textbox<OasysDate>('#P6_DATE_AMENDED')
    sentence = new Element.Select('#P6_SENTENCE_CODE')
    disqualificationOrder = new Element.Select('#P6_DISQUALIFICATION_ORDER')
    custodyInMonths = new Element.Textbox('#P6_SENTENCE_LENGTH_CRO_M')
    sentenceLengthInDays = new Element.Textbox('#P6_SENTENCE_LENGTH_CUST_DAYS')
    communityPunishmentHours = new Element.Textbox('#P6_SENTENCE_LENGTH_CPO_HOURS')
    sentenceDate = new Element.Textbox<OasysDate>('#P6_SENTENCE_DATE')
    courtProximity = new Element.Select('#P6_COURT_PROXIMITY')
    courtName = new Element.Lov('#P6_COURT_NAME_LABEL')
    courtType = new Element.Textbox('#P6_COURT_TYPE')
    orderLengthMonths = new Element.Textbox('#P6_CJA_ORDER_LENGTH')
    unpaidWork = new Element.Select('#P6_CJA_REQ_UNPAID_WORK')
    unpaidWorkHours = new Element.Textbox('#P6_CJA_UNPAID_HOURS')
    activity = new Element.Select('#P6_CJA_REQ_ACTIVITY')
    victimReparation = new Element.Select('#P6_CJA_ACT_VICTIM')
    education = new Element.Select('#P6_CJA_ACT_EDUCATION')
    financial = new Element.Select('#P6_CJA_ACT_FINANCE')
    accommodation = new Element.Select('#P6_CJA_ACT_ACCOMMODATION')
    other = new Element.Select('#P6_CJA_ACT_OTHER')
    otherDescription = new Element.Textbox('#P6_CJA_ACT_OTHER_ZDESC')
    accreditedProgramme = new Element.Select('#P6_CJA_REQ_ACCTED_PROG')
    accreditedProgramme1 = new Element.Select('#P6_CJA_ACCTED_PROG_NAME_ELM1')
    accreditedProgramme2 = new Element.Select('#P6_CJA_ACCTED_PROG_NAME_ELM2')
    accreditedProgramme3 = new Element.Select('#P6_CJA_ACCTED_PROG_NAME_ELM3')
    accreditedProgramme4 = new Element.Select('#P6_CJA_ACCTED_PROG_NAME_ELM4')
    prohibitedActivity = new Element.Select('#P6_CJA_REQ_PROHBT_ACTIVITY')
    prohibitedActivity1 = new Element.Textbox('#P6_PROHBT_ACTIVITY_ZDESC1')
    prohibitedActivity2 = new Element.Textbox('#P6_PROHBT_ACTIVITY_ZDESC2')
    prohibitedActivity3 = new Element.Textbox('#P6_PROHBT_ACTIVITY_ZDESC3')
    curfew = new Element.Select('#P6_CJA_REQ_CURFEW')
    exclusion = new Element.Select('#P6_CJA_REQ_EXCLUSION')
    residence = new Element.Select('#P6_CJA_REQ_RESIDENCE')
    mentalHealthTreatment = new Element.Select('#P6_CJA_REQ_MENTAL_HEALTH')
    drugRehabilitation = new Element.Select('#P6_CJA_REQ_DRUG_REHAB')
    alcoholTreatment = new Element.Select('#P6_CJA_REQ_ALCOHOL')
    supervision = new Element.Select('#P6_CJA_REQ_SUPERVISION')
    supervisionMonths = new Element.Textbox('#P6_CJA_SUPERVISION_MONTHS')
    attendanceCentre = new Element.Select('#P6_CJA_REQ_ATTENDANCE')
    electronicMonitoring = new Element.Select('#P6_CJA_REQ_ELEC_MONITORING')
    drugTesting = new Element.Select('#P6_CJA_REQ_DRUG_TESTING')
    intoxicatingSubstanceTreatment = new Element.Select('#P6_CJA_REQ_INTOX_SUBST_TRTMNT')
    alcoholMonitoring = new Element.Select('#P6_ALCMON')
    additionalRequirements1 = new Element.Select('#P6_ADDL_SENTENCE_REQUIRE_ELM1')
    additionalRequirements2 = new Element.Select('#P6_ADDL_SENTENCE_REQUIRE_ELM2')
    additionalRequirements3 = new Element.Select('#P6_ADDL_SENTENCE_REQUIRE_ELM3')
    additionalRequirements4 = new Element.Select('#P6_ADDL_SENTENCE_REQUIRE_ELM4')
    additionalRequirements5 = new Element.Select('#P6_ADDL_SENTENCE_REQUIRE_ELM5')
    specificInterventions1 = new Element.Select('#P6_INTERVENTION_ELM1')
    specificInterventions2 = new Element.Select('#P6_INTERVENTION_ELM2')
    specificInterventions3 = new Element.Select('#P6_INTERVENTION_ELM3')
    licenceInformation = new Element.Select('#P6_LICENCE_TITLE')
    sentenceAdditionalLicenceConditions = new Element.Textbox('#P6_SNT_ALIC_CNDS2_LGCYDAT')
    dateOfActualRelease = new Element.Textbox<OasysDate>('#P6_DATE_OF_ACTUAL_RELEASE')
    typeOfRelease = new Element.Select('#P6_RELEASE_TYPE_ELM')
    anyLicenceRequirements = new Element.Textbox('#P6_LICENCE_REQUIRE_RELEASE')
    homeDetentionCurfewDate = new Element.Textbox<OasysDate>('#P6_HOME_DETN_CURFEW_DATE')
    automaticReleaseDate = new Element.Textbox<OasysDate>('#P6_AUTOMATIC_RELEASE_DATE')
    conditionalReleaseDate = new Element.Textbox<OasysDate>('#P6_CONDITIONAL_RELEASE_DATE')
    paroleEligibilityDate = new Element.Textbox<OasysDate>('#P6_PAROLE_ELIGIBILITY_DATE')
    nonParoleDate = new Element.Textbox<OasysDate>('#P6_NON_PAROLE_DATE')
    licenceExpiryDate = new Element.Textbox<OasysDate>('#P6_LICENCE_EXPIRY_DATE')
    resettlementLicenceEligibilityDate = new Element.Textbox<OasysDate>('#P6_RESETTLE_LIC_ELIG_DATE')
    sentenceExpiryDate = new Element.Textbox<OasysDate>('#P6_SENTENCE_EXPIRY_DATE')
    recallDate = new Element.Textbox<OasysDate>('#P6_RECALL_DATE')
    postSentenceSupervisionExpiryDate = new Element.Textbox<OasysDate>('#P6_POST_SENT_SUPV_DATE')
    detainedUnderImmigrationAct = new Element.Select('#P6_DET_U_IMMIGRATION_ACT_IND')
    recommendedForDeportation = new Element.Select('#P6_RECOMMENDED_DEP_IND')
    furtherChargesPending = new Element.Select('#P6_CHARGES_PENDING_IND')
    furtherChargesPendingDetails = new Element.Textbox('#P6_CHARGES_PENDING_DTL')
    appealPending = new Element.Select('#P6_APPEAL_PENDING_INDICATOR')
    appealPendingDetails = new Element.Textbox('#P6_APPEAL_PENDING_DETAILS')
}


