import { Page } from 'classes/page'
import * as Element from 'classes/elements'

export class GlobalProfile extends Page {

    name = 'GlobalProfile'
    title = 'Global Profile Maintenance'
    menu: Menu = { type: 'Main', level1: 'Maintenance', level2: 'Global Profile' }

    save = new Element.Button('Save')
    close = new Element.Button('Close')
    timeoutPeriod = new Element.Textbox('#P7_SEC_SESSION_TIMEOUT_SECONDS')
    notificationTaskTimeLimit = new Element.Textbox('#P7_NOTIF_COMP_DAYS')
    deleteCompletedTasks = new Element.Textbox('#P7_DEL_COMP_TASKS')
    normalReviewPeriodPrison = new Element.Textbox('#P7_REV_NORM_PRIS')
    normalReviewPeriodProbation = new Element.Textbox('#P7_REV_NORM_PROB')
    reviewRemindersDuePrison = new Element.Textbox('#P7_REV_REM_WEEKS_PRIS')
    reviewRemindersDueProbation = new Element.Textbox('#P7_REV_REM_WEEKS_PROB')
    terminationRemindersDue = new Element.Textbox('#P7_TERM_REM_WEEKS')
    timeLimitCloningTerminatedAssessments = new Element.Textbox('#P7_CLONE_LIMIT_MNTHS')
    timeLimitCloningBcsPart1 = new Element.Textbox('#P7_TR_BCS_CLONE_LIMIT_WEEKS')
    allowRollback = new Element.Textbox('#P7_ROLLBACK_DAYS')
    previousOrderCompletionPeriod = new Element.Textbox('#P7_PREV_COMP_DAYS')
    rfaExpiryTimePeriod = new Element.Textbox('#P7_RFA_EXP_DAYS')
    maxRfaTimePeriod = new Element.Textbox('#P7_MAX_RFA_TIME_DAYS')
    dueDateTransferCountersignature = new Element.Textbox<OasysDate>('#P7_TRM_WAIT_CS_DUE_DATE')
    dueDateTransferDecision = new Element.Textbox<OasysDate>('#P7_TRM_WAIT_DEC_DUE_DATE')
    dueDateTransferReqReceivedCountersignature = new Element.Textbox<OasysDate>('#P7_TRR_WAIT_CS_DUE_DATE')
    dueDateTransferAwaitingDecision = new Element.Textbox<OasysDate>('#P7_TRR_DEC_REQ_DUE_DATE')
    dueDateMergeDecisionRequired = new Element.Textbox<OasysDate>('#P7_MER_NOWIP_DEC_DUE_DATE')
    dueDateMergeAwaitingDecision = new Element.Textbox<OasysDate>('#P7_MER_NOWIP_WAIT_DUE_DATE')
    dueDateCountersign = new Element.Textbox<OasysDate>('#P7_CS_DUE_DATE')
    dueDatePsrCountersign = new Element.Textbox<OasysDate>('#P7_PSR_CS_DUE_DATE')
    dueDateRequestForAccess = new Element.Textbox<OasysDate>('#P7_RFA_DUE_DATE')
    dueDateSentenceBoardComments = new Element.Textbox<OasysDate>('#P7_SEN_BRD_COM_DUE_DATE')
    eventAuditLevel = new Element.Select('#P7_EVENT_AUDIT_LEVEL')
    deleteAuditableEvents = new Element.Textbox('#P7_DELETE_AUDITABLE_EVENTS')
    communityPunishmentHours = new Element.Textbox('#P7_CP_HOURS')
    psrCreationConditions = new Element.Select('#P7_PSR_CREATION_CONDS')
    copyrightText = new Element.Textbox('#P7_COURT_RPT_COPYRIGHT_TEXT')
    assessmentCompletionTimePeriod = new Element.Textbox('#P7_ASSMT_COMP_TIME_DAYS')
    standardAssessmentGuillotine = new Element.Textbox('#P7_STD_ASSMT_GUIL')
    createCommunityGuillotine = new Element.Textbox('#P7_START_COMM_GUIL')
    createNonCommunityGuillotine = new Element.Textbox('#P7_CREATE_ASSMT_GUIL')
    bcsPart1CompletionTimePeriod = new Element.Textbox('#P7_BCS_PART_1_GUIL')
    bcsPart2CompletionTimePeriod = new Element.Textbox('#P7_BCS_PART_2_GUIL')
    transferRequestGrantedGuillotine = new Element.Textbox('#P7_TRAN_REQ_GUIL')
    setOmFlagGuillotine = new Element.Textbox('#P7_OM_FLAG_GUIL')
    offenderChangesPrisonGuillotine = new Element.Textbox('#P7_OFF_CHG_PRIS_GUIL')
    offenderReleasedGuillotine = new Element.Textbox('#P7_OFF_REL_PRIS_GUIL')
    dpaNotice = new Element.TextEditor('#P7_SEC_DPA_MESSAGE_LABEL')
    passwordExpiryPeriod = new Element.Textbox('#P7_SEC_PASSWORD_LIFE_TIME')
    noOfLoginAttempts = new Element.Textbox('#P7_SEC_FAILED_LOGIN_ATTEMPTS')
    showForgotPasswordButton = new Element.Radiogroup('#P7_FORGOT_PWD')
    rollbackQaReviewPrison = new Element.Textbox('#P7_ROLLBACK_QA_DAYS_PRIS')
    rollbackQaReviewProbation = new Element.Textbox('#P7_ROLLBACK_QA_DAYS_PROB')
    dataRetentionPeriodNonStatutory = new Element.Textbox('#P7_DATA_RET_PERIOD_NON_STAT')
    dataRetentionPeriodStatutory = new Element.Textbox('#P7_DATA_RET_PERIOD_STAT')
    dataRetentionPeriodLifers = new Element.Textbox('#P7_DATA_RET_LIFE')
    forceCrnProvision = new Element.Radiogroup('#P7_PROB_FORCE_CRN')
    timeLimitDisablingUserAccounts = new Element.Textbox('#P7_DEACT_USER_DAYS')
    warningDisablingUserAccounts = new Element.Textbox('#P7_DISABLE_WARNING_DAYS')
    learningScreeningTool = new Element.Radiogroup('#P7_LEARNING_SCREENING_TOOL')
    tspMonthsLeftToServe = new Element.Textbox('#P7_TSP_MONTHS_LEFT_TO_SERVE')
    rsrAlgorithmVersion = new Element.Textbox('#P7_RSR_ALGORITHM_VERSION')
    ospShown = new Element.Radiogroup('#P7_OSP_ON_SCREEN')
}
