export * as IspSection1to4 from './ispSection1to4'
export * as IspSection5 from './ispSection5'
export * as IspSection52to8 from './ispSection52to8'
export * as RspSection1to2 from './rspSection1to2'
export * as RspSection3to63 from './rspSection3to63'
export * as RspSection7 from './rspSection7'
export * as RspSection72to10 from './rspSection72to10'
export * as ObjectivesAndActions from './objectivesAndActions'