import * as oasys from 'oasys'

/**
 * Fully populates a SARA assessment
 */
export function sara(riskToPartner: 'Low' | 'Medium' | 'High', riskToOther: 'Low' | 'Medium' | 'High') {

    cy.log('Populating SARA')

    const sara = new oasys.Pages.Sara.Sara().goto()

    sara.s1Rating.setValue('P')
    sara.s1Critical.setValue('Yes')
    sara.s1Comments.setValue('Comment')
    sara.s2Rating.setValue('P')
    sara.s2Critical.setValue('Yes')
    sara.s2Comments.setValue('Comment')
    sara.s3Rating.setValue('Y')
    sara.s3Critical.setValue('Yes')
    sara.s3Comments.setValue('Comment')
    sara.s4Rating.setValue('P')
    sara.s4Critical.setValue('Yes')
    sara.s4Comments.setValue('Comment')
    sara.s5Rating.setValue('P')
    sara.s5Critical.setValue('Yes')
    sara.s5Comments.setValue('Comment')
    sara.s6Rating.setValue('Y')
    sara.s6Critical.setValue('Yes')
    sara.s6Comments.setValue('Comment')
    sara.s7Rating.setValue('P')
    sara.s7Critical.setValue('Yes')
    sara.s7Comments.setValue('Comment')
    sara.s8Rating.setValue('Y')
    sara.s8Critical.setValue('Yes')
    sara.s8Comments.setValue('Comment')
    sara.s9Rating.setValue('P')
    sara.s9Critical.setValue('Yes')
    sara.s9Comments.setValue('Comment')
    sara.s10Rating.setValue('P')
    sara.s10Critical.setValue('Yes')
    sara.s10Comments.setValue('Comment')
    sara.s11Rating.setValue('P')
    sara.s11Critical.setValue('Yes')
    sara.s11Comments.setValue('Comment')
    sara.s12Rating.setValue('Y')
    sara.s12Critical.setValue('Yes')
    sara.s12Comments.setValue('Comment')
    sara.s13Rating.setValue('P')
    sara.s13Critical.setValue('Yes')
    sara.s13Comments.setValue('Comment')
    sara.s14Rating.setValue('Y')
    sara.s14Critical.setValue('Yes')
    sara.s14Comments.setValue('Comment')
    sara.s15Rating.setValue('P')
    sara.s15Critical.setValue('Yes')
    sara.s15Comments.setValue('Comment')
    sara.s16Rating.setValue('Y')
    sara.s16Critical.setValue('Yes')
    sara.s16Comments.setValue('Comment')
    sara.s17Rating.setValue('P')
    sara.s17Critical.setValue('Yes')
    sara.s17Comments.setValue('Comment')
    sara.s18Rating.setValue('Y')
    sara.s18Critical.setValue('Yes')
    sara.s18Comments.setValue('Comment')
    sara.s19Rating.setValue('P')
    sara.s19Critical.setValue('Yes')
    sara.s19Comments.setValue('Comment')
    sara.s20Rating.setValue('P')
    sara.s20Critical.setValue('Yes')
    sara.s20Comments.setValue('Comment')
    sara.otherConsideration1.setValue('Other consideration 1')
    sara.otherConsideration1Rating.setValue('P')
    sara.riskOfViolencePartner.setValue(riskToPartner)
    sara.riskOfViolenceOthers.setValue(riskToOther)
    sara.interviewWithOffender.setValue('Yes')
    sara.interviewWithVictims.setValue('Yes')
    sara.interviewWithOthers.setValue('Yes')
    sara.sourcesComments1.setValue('Sources')
    sara.sourcesComments2.setValue('Sources')
    sara.sourcesComments3.setValue('Sources')
    sara.offenderTestsA.setValue('Yes')
    sara.offenderTestsB.setValue('Yes')
    sara.offenderTestsC.setValue('Yes')
    sara.offenderTestsD.setValue('Yes')
    sara.victimTestsA.setValue('Yes')
    sara.victimTestsB.setValue('Yes')
    sara.victimTestsC.setValue('Yes')
    sara.victimTestsD.setValue('Yes')
}