import * as oasys from 'oasys'

export function minimal() {

    const page = new oasys.Pages.Assessment.SelfAssessmentForm().goto(true)

    page.whyNotCompleted.setValue(`Didn't want to`)
}


export function fullyPopulated(maxStrings: boolean = false) {

    const page = new oasys.Pages.Assessment.SelfAssessmentForm().goto(true)

    page.helpNeeded.setValue('Yes')
    page.dateCompleted.setValue({})
    page.s1.setValue('Yes')
    page.s1LinkedOffending.setValue('Yes')
    page.s2.setValue('Yes')
    page.s2LinkedOffending.setValue('Yes')
    page.s3.setValue('Yes')
    page.s3LinkedOffending.setValue('Yes')
    page.s4.setValue('Yes')
    page.s4LinkedOffending.setValue('Yes')
    page.s5.setValue('Yes')
    page.s5LinkedOffending.setValue('Yes')
    page.s6.setValue('Yes')
    page.s6LinkedOffending.setValue('Yes')
    page.s7.setValue('Yes')
    page.s7LinkedOffending.setValue('Yes')
    page.s8.setValue('Yes')
    page.s8LinkedOffending.setValue('Yes')
    page.s9.setValue('Yes')
    page.s9LinkedOffending.setValue('Yes')
    page.s10.setValue('Yes')
    page.s10LinkedOffending.setValue('Yes')
    page.s11.setValue('Yes')
    page.s11LinkedOffending.setValue('Yes')
    page.s12.setValue('Yes')
    page.s12LinkedOffending.setValue('Yes')
    page.s13.setValue('Yes')
    page.s13LinkedOffending.setValue('Yes')
    page.s14.setValue('Yes')
    page.s14LinkedOffending.setValue('Yes')
    page.s15.setValue('Yes')
    page.s15LinkedOffending.setValue('Yes')
    page.s16.setValue('Yes')
    page.s16LinkedOffending.setValue('Yes')
    page.s17.setValue('Yes')
    page.s17LinkedOffending.setValue('Yes')
    page.s18.setValue('Yes')
    page.s18LinkedOffending.setValue('Yes')
    page.s19.setValue('Yes')
    page.s19LinkedOffending.setValue('Yes')
    page.s20.setValue('Yes')
    page.s20LinkedOffending.setValue('Yes')
    page.s21.setValue('Yes')
    page.s21LinkedOffending.setValue('Yes')
    page.s22.setValue('Yes')
    page.s22LinkedOffending.setValue('Yes')
    page.s23.setValue('Yes')
    page.s23LinkedOffending.setValue('Yes')
    page.s24.setValue('Yes')
    page.s24LinkedOffending.setValue('Yes')
    page.s25.setValue('Yes')
    page.s25LinkedOffending.setValue('Yes')
    page.s26.setValue('Yes')
    page.s26LinkedOffending.setValue('Yes')
    page.s27.setValue('Yes')
    page.s27LinkedOffending.setValue('Yes')
    page.s28.setValue('Quite likely')
    page.why.setValue(maxStrings ? oasys.oasysString(4000) : `Because I'm a criminal`)
    page.save.click()
}