import * as oasys from 'oasys'


export function noIssues() {

    const page = new oasys.Pages.Assessment.Section8().goto(true)
    page.o8_1.setValue('No')
}

export function fullyPopulated(maxStrings: boolean = false) {

    const page = new oasys.Pages.Assessment.Section8().goto(true)
    page.o8_1.setValue('Yes')
    page.aCurrent.setValue('Daily')
    page.aCurrentlyInjected.setValue(true)
    page.aPrevious.setValue(true)
    page.aPreviouslyInjected.setValue(true)
    page.bCurrent.setValue('Weekly')
    page.bCurrentlyInjected.setValue(true)
    page.bPrevious.setValue(true)
    page.bPreviouslyInjected.setValue(true)
    page.cCurrent.setValue('Monthly')
    page.cCurrentlyInjected.setValue(true)
    page.cPrevious.setValue(true)
    page.cPreviouslyInjected.setValue(true)
    page.dCurrent.setValue('Occasional')
    page.dCurrentlyInjected.setValue(true)
    page.dPrevious.setValue(true)
    page.dPreviouslyInjected.setValue(true)
    page.eCurrent.setValue('Daily')
    page.eCurrentlyInjected.setValue(true)
    page.ePrevious.setValue(true)
    page.ePreviouslyInjected.setValue(true)
    page.fCurrent.setValue('Weekly')
    page.fCurrentlyInjected.setValue(true)
    page.fPrevious.setValue(true)
    page.fPreviouslyInjected.setValue(true)
    page.gCurrent.setValue('Monthly')
    page.gCurrentlyInjected.setValue(true)
    page.gPrevious.setValue(true)
    page.gPreviouslyInjected.setValue(true)
    page.hCurrent.setValue('Daily')
    page.hCurrentlyInjected.setValue(true)
    page.hPrevious.setValue(true)
    page.hPreviouslyInjected.setValue(true)
    page.iCurrent.setValue('Weekly')
    page.iPrevious.setValue(true)
    page.jCurrent.setValue('Monthly')
    page.jPrevious.setValue(true)
    page.kCurrent.setValue('Occasional')
    page.kPrevious.setValue(true)
    page.lCurrent.setValue('Daily')
    page.lPrevious.setValue(true)
    page.mCurrent.setValue('Weekly')
    page.mCurrentlyInjected.setValue(true)
    page.mPrevious.setValue(true)
    page.mPreviouslyInjected.setValue(true)
    page.pCurrent.setValue('Monthly')
    page.pPrevious.setValue(true)
    page.nCurrent.setValue('Occasional')
    page.nCurrentlyInjected.setValue(true)
    page.nPrevious.setValue(true)
    page.nPreviouslyInjected.setValue(true)

    page.other.setValue(maxStrings ? oasys.oasysString(256) : 'Some other stuff from time to time')
    page.o8_8.setValue('2-Significant problems')
    page.o8_9.setValue('2-Significant problems')
    page.identifyIssues.setValue(maxStrings ? oasys.oasysString(4000) : 'Section 8 issues')
    page.linkedToRisk.setValue('Yes')
    page.linkedToBehaviour.setValue('Yes')
}
