import * as oasys from 'oasys'


export function noIssues() {

    const page = new oasys.Pages.Assessment.Section13().goto(true)
    page.noIssues.click()
}

export function fullyPopulated(maxStrings: boolean = false) {

    const page = new oasys.Pages.Assessment.Section13().goto(true)
    page.o13_1.setValue('Yes')
    page.o13_1Details.setValue(maxStrings ? oasys.oasysString(4000) : '13.1Details text')
    page.o13_2Impact.setValue('Yes')
    page.o13_2ImpactDetails.setValue(maxStrings ? oasys.oasysString(4000) : '13.2ImpactDetails text')
    page.o13_2Electricity.setValue('Yes')
    page.chronicCommunity.setValue(true)
    page.chronicCommunityDetails.setValue(maxStrings ? oasys.oasysString(256) : 'ChronicCommunityDetails text')
    page.chronicEm.setValue(true)
    page.chronicEmDetails.setValue(maxStrings ? oasys.oasysString(256) : 'ChronicEmDetails text')
    page.chronicProgramme.setValue(true)
    page.chronicProgrammeDetails.setValue(maxStrings ? oasys.oasysString(256) : 'ChronicProgrammeDetails text')
    page.disabilityCommunity.setValue(true)
    page.disabilityCommunityDetails.setValue(maxStrings ? oasys.oasysString(256) : 'DisabilityCommunityDetails text')
    page.disabilityEm.setValue(true)
    page.disabilityEmDetails.setValue(maxStrings ? oasys.oasysString(256) : 'DisabilityEmDetails text')
    page.disabilityProgramme.setValue(true)
    page.disabilityProgrammeDetails.setValue(maxStrings ? oasys.oasysString(256) : 'DisabilityProgrammeDetails text')
    page.psychiatricCommunity.setValue(true)
    page.psychiatricCommunityDetails.setValue(maxStrings ? oasys.oasysString(256) : 'PsychiatricCommunityDetails text')
    page.psychiatricEm.setValue(true)
    page.psychiatricEmDetails.setValue(maxStrings ? oasys.oasysString(256) : 'PsychiatricEmDetails text')
    page.psychiatricProgramme.setValue(true)
    page.psychiatricProgrammeDetails.setValue(maxStrings ? oasys.oasysString(256) : 'PsychiatricProgrammeDetails text')
    page.motivationCommunity.setValue(true)
    page.motivationCommunityDetails.setValue(maxStrings ? oasys.oasysString(256) : 'MotivationCommunityDetails text')
    page.motivationEm.setValue(true)
    page.motivationEmDetails.setValue(maxStrings ? oasys.oasysString(256) : 'MotivationEmDetails text')
    page.motivationProgramme.setValue(true)
    page.motivationProgrammeDetails.setValue(maxStrings ? oasys.oasysString(256) : 'MotivationProgrammeDetails text')
    page.learningCommunity.setValue(true)
    page.learningCommunityDetails.setValue(maxStrings ? oasys.oasysString(256) : 'LearningCommunityDetails text')
    page.learningEm.setValue(true)
    page.learningEmDetails.setValue(maxStrings ? oasys.oasysString(256) : 'LearningEmDetails text')
    page.learningProgramme.setValue(true)
    page.learningProgrammeDetails.setValue(maxStrings ? oasys.oasysString(256) : 'LearningProgrammeDetails text')
    page.literacyCommunity.setValue(true)
    page.literacyCommunityDetails.setValue(maxStrings ? oasys.oasysString(256) : 'LiteracyCommunityDetails text')
    page.literacyEm.setValue(true)
    page.literacyEmDetails.setValue(maxStrings ? oasys.oasysString(256) : 'LiteracyEmDetails text')
    page.literacyProgramme.setValue(true)
    page.literacyProgrammeDetails.setValue(maxStrings ? oasys.oasysString(256) : 'LiteracyProgrammeDetails text')
    page.communicationCommunity.setValue(true)
    page.communicationCommunityDetails.setValue(maxStrings ? oasys.oasysString(256) : 'CommunicationCommunityDetails text')
    page.communicationEm.setValue(true)
    page.communicationEmDetails.setValue(maxStrings ? oasys.oasysString(256) : 'CommunicationEmDetails text')
    page.communicationProgramme.setValue(true)
    page.communicationProgrammeDetails.setValue(maxStrings ? oasys.oasysString(256) : 'CommunicationProgrammeDetails text')
    page.interpreterCommunity.setValue(true)
    page.interpreterCommunityDetails.setValue(maxStrings ? oasys.oasysString(256) : 'InterpreterCommunityDetails text')
    page.interpreterEm.setValue(true)
    page.interpreterEmDetails.setValue(maxStrings ? oasys.oasysString(256) : 'InterpreterEmDetails text')
    page.interpreterProgramme.setValue(true)
    page.interpreterProgrammeDetails.setValue(maxStrings ? oasys.oasysString(256) : 'InterpreterProgrammeDetails text')
    page.alcoholCommunity.setValue(true)
    page.alcoholCommunityDetails.setValue(maxStrings ? oasys.oasysString(256) : 'AlcoholCommunityDetails text')
    page.alcoholEm.setValue(true)
    page.alcoholEmDetails.setValue(maxStrings ? oasys.oasysString(256) : 'AlcoholEmDetails text')
    page.alcoholProgramme.setValue(true)
    page.alcoholProgrammeDetails.setValue(maxStrings ? oasys.oasysString(256) : 'AlcoholProgrammeDetails text')
    page.drugsCommunity.setValue(true)
    page.drugsCommunityDetails.setValue(maxStrings ? oasys.oasysString(256) : 'DrugsCommunityDetails text')
    page.drugsEm.setValue(true)
    page.drugsEmDetails.setValue(maxStrings ? oasys.oasysString(256) : 'DrugsEmDetails text')
    page.drugsProgramme.setValue(true)
    page.drugsProgrammeDetails.setValue(maxStrings ? oasys.oasysString(256) : 'DrugsProgrammeDetails text')
    page.lifestyleCommunity.setValue(true)
    page.lifestyleCommunityDetails.setValue(maxStrings ? oasys.oasysString(256) : 'LifestyleCommunityDetails text')
    page.lifestyleEm.setValue(true)
    page.lifestyleEmDetails.setValue(maxStrings ? oasys.oasysString(256) : 'LifestyleEmDetails text')
    page.lifestyleProgramme.setValue(true)
    page.lifestyleProgrammeDetails.setValue(maxStrings ? oasys.oasysString(256) : 'LifestyleProgrammeDetails text')
    page.religionCommunity.setValue(true)
    page.religionCommunityDetails.setValue(maxStrings ? oasys.oasysString(256) : 'ReligionCommunityDetails text')
    page.religionEm.setValue(true)
    page.religionEmDetails.setValue(maxStrings ? oasys.oasysString(256) : 'ReligionEmDetails text')
    page.religionProgramme.setValue(true)
    page.religionProgrammeDetails.setValue(maxStrings ? oasys.oasysString(256) : 'ReligionProgrammeDetails text')
    page.transportCommunity.setValue(true)
    page.transportCommunityDetails.setValue(maxStrings ? oasys.oasysString(256) : 'TransportCommunityDetails text')
    page.transportEm.setValue(true)
    page.transportEmDetails.setValue(maxStrings ? oasys.oasysString(256) : 'TransportEmDetails text')
    page.transportProgramme.setValue(true)
    page.transportProgrammeDetails.setValue(maxStrings ? oasys.oasysString(256) : 'TransportProgrammeDetails text')
    page.employmentCommunity.setValue(true)
    page.employmentCommunityDetails.setValue(maxStrings ? oasys.oasysString(256) : 'EmploymentCommunityDetails text')
    page.employmentEm.setValue(true)
    page.employmentEmDetails.setValue(maxStrings ? oasys.oasysString(256) : 'EmploymentEmDetails text')
    page.employmentProgramme.setValue(true)
    page.employmentProgrammeDetails.setValue(maxStrings ? oasys.oasysString(256) : 'EmploymentProgrammeDetails text')
    page.educationCommunity.setValue(true)
    page.educationCommunityDetails.setValue(maxStrings ? oasys.oasysString(256) : 'EducationCommunityDetails text')
    page.educationEm.setValue(true)
    page.educationEmDetails.setValue(maxStrings ? oasys.oasysString(256) : 'EducationEmDetails text')
    page.educationProgramme.setValue(true)
    page.educationProgrammeDetails.setValue(maxStrings ? oasys.oasysString(256) : 'EducationProgrammeDetails text')
    page.carersCommunity.setValue(true)
    page.carersCommunityDetails.setValue(maxStrings ? oasys.oasysString(256) : 'CarersCommunityDetails text')
    page.carersEm.setValue(true)
    page.carersEmDetails.setValue(maxStrings ? oasys.oasysString(256) : 'CarersEmDetails text')
    page.carersProgramme.setValue(true)
    page.carersProgrammeDetails.setValue(maxStrings ? oasys.oasysString(256) : 'CarersProgrammeDetails text')
    page.o13_4.setValue('Yes')
}
