import * as oasys from 'oasys'


export function noIssues() {

    const page = new oasys.Pages.Assessment.Section2().goto(true)
    page.o2_2Weapon.setValue('No')
    page.o2_2Violence.setValue('No')
    page.o2_2ExcessiveViolence.setValue('No')
    page.o2_2Arson.setValue('No')
    page.impactRecognised.setValue('Yes')
    page.o2_9Emotional.setValue('No')
    page.o2_14.setValue('No')
    page.identifyIssues.setValue('Section 2 no issues')
    page.linkedToRisk.setValue('No')
}

export function fullyPopulated(maxStrings: boolean = false) {

    const page = new oasys.Pages.Assessment.Section2().goto(true)
    page.briefOffenceDetails.setValue(maxStrings ? oasys.oasysString(4000) : 'Brief offence details')
    page.o2_2Weapon.setValue('Yes')
    page.o2_2SpecifyWeapon.setValue(maxStrings ? oasys.oasysString(96) : 'A big knife')
    page.o2_2Violence.setValue('Yes')
    page.o2_2ExcessiveViolence.setValue('Yes')
    page.o2_2Arson.setValue('Yes')
    page.o2_2PhysicalDamage.setValue('Yes')
    page.o2_2Sexual.setValue('Yes')
    page.o2_2DomesticAbuse.setValue('Yes')
    page.o2_3Direct.setValue(true)
    page.o2_3Hate.setValue(true)
    page.o2_3ResponseToVictim.setValue(true)
    page.o2_3PhysicalViolence.setValue(true)
    page.o2_3RepeatVictimisation.setValue(true)
    page.o2_3Strangers.setValue(true)
    page.o2_3Stalking.setValue(true)
    page.o2_4Relationship.setValue(maxStrings ? oasys.oasysString(4000) : 'Victim - perp relationship')
    page.o2_4OtherInformation.setValue(maxStrings ? oasys.oasysString(4000) : 'Other information about victims')
    page.impactOnVictim.setValue(maxStrings ? oasys.oasysString(4000) : 'Impact on the victim')
    page.impactRecognised.setValue('Yes')
    page.o2_7OtherOffenders.setValue('Yes')
    page.o2_7Number.setValue('1')
    page.o2_7PeerGroup.setValue('Yes')
    page.o2_7Leader.setValue(maxStrings ? oasys.oasysString(4000) : 'Offender was the leader')
    page.o2_8.setValue(maxStrings ? oasys.oasysString(4000) : 'Why did it happen?')
    page.o2_9Sexual.setValue('Yes')
    page.o2_9Financial.setValue('Yes')
    page.o2_9Addiction.setValue('Yes')
    page.o2_9Emotional.setValue('Yes')
    page.o2_9Racial.setValue('Yes')
    page.o2_9Thrill.setValue('Yes')
    page.o2_9Other.setValue('Yes')
    page.o2_9OtherDetails.setValue(maxStrings ? oasys.oasysString(128) : 'Some other motivation')
    page.o2_10Alcohol.setValue(true)
    page.o2_10Pornography.setValue(true)
    page.o2_10Medication.setValue(true)
    page.o2_10Psychiactric.setValue(true)
    page.o2_10Emotional.setValue(true)
    page.o2_10Drugs.setValue(true)
    page.o2_10Trauma.setValue(true)
    page.o2_11.setValue('Yes')
    page.o2_11Details.setValue(maxStrings ? oasys.oasysString(4000) : 'How much responsibility')
    page.o2_12.setValue(maxStrings ? oasys.oasysString(4000) : 'Pattern of offending')
    page.o2_13.setValue('Yes')
    page.o2_14.setValue('Yes')
    page.identifyIssues.setValue(maxStrings ? oasys.oasysString(4000) : 'Section 2 issues')
    page.linkedToRisk.setValue('Yes')

    oasys.Populate.CommonPages.Victims.victim1()
    oasys.Populate.CommonPages.Victims.victim2()
}