import * as oasys from 'oasys'

export function minimal(withDateFirstSanction: boolean = true) {

    const page = new oasys.Pages.Assessment.RoshaPredictors()
    page.goto(true)
    if (withDateFirstSanction) {
        page.dateFirstSanction.setValue({ years: -2 })
    }
    page.o1_32.setValue('1')
    page.o1_40.setValue(0)
    page.o1_29.setValue({ days: -7 })
    page.o1_30.setValue('No')
    page.o1_38.setValue({ months: 18 })
}

export function fullyPopulated(withDateFirstSanction: boolean = true) {

    const page = new oasys.Pages.Assessment.RoshaPredictors()
    page.goto(true)
    if (withDateFirstSanction) {
        page.dateFirstSanction.setValue({ years: -2 })
    }
    page.o1_32.setValue('5')
    page.o1_40.setValue('1')
    page.o1_29.setValue({ days: -7 })
    page.o1_30.setValue('Yes')
    page.o1_41.setValue('Yes')
    page.o1_44.setValue('Yes')
    page.o1_33.setValue({ years: -5 })
    page.o1_34.setValue('0')
    page.o1_45.setValue('0')
    page.o1_46.setValue('0')
    page.o1_37.setValue('2')
    page.o1_38.setValue({ months: 18 })
    page.o1_39.setValue('Yes')
    page.o2_2.setValue('Yes')
    page.o2_2Weapon.setValue('A knife')
    page.o3_4.setValue('1-Some problems')
    page.o4_2.setValue('2-Yes')
    page.o6_4.setValue('2-Significant problems')
    page.o6_7.setValue('Yes')
    page.o6_7VictimPartner.setValue('No')
    page.o6_7VictimFamily.setValue('Yes')
    page.o6_7PerpetratorPartner.setValue('No')
    page.o6_7PerpetratorFamily.setValue('No')
    page.o6_8.setValue('In a relationship, living together')
    page.o7_2.setValue('1-Some problems')
    page.o8_1.setValue('Yes')
    page.aCurrent.setValue('Daily')
    page.aCurrentlyInjected.setValue(true)
    page.aPrevious.setValue(true)
    page.aPreviouslyInjected.setValue(true)
    page.bCurrent.setValue('Weekly')
    page.bCurrentlyInjected.setValue(true)
    page.bPrevious.setValue(true)
    page.bPreviouslyInjected.setValue(true)
    page.cCurrent.setValue('Monthly')
    page.cCurrentlyInjected.setValue(true)
    page.cPrevious.setValue(true)
    page.cPreviouslyInjected.setValue(true)
    page.dCurrent.setValue('Occasional')
    page.dCurrentlyInjected.setValue(true)
    page.dPrevious.setValue(true)
    page.dPreviouslyInjected.setValue(true)
    page.eCurrent.setValue('Daily')
    page.eCurrentlyInjected.setValue(true)
    page.ePrevious.setValue(true)
    page.ePreviouslyInjected.setValue(true)
    page.fCurrent.setValue('Weekly')
    page.fCurrentlyInjected.setValue(true)
    page.fPrevious.setValue(true)
    page.fPreviouslyInjected.setValue(true)
    page.gCurrent.setValue('Monthly')
    page.gCurrentlyInjected.setValue(true)
    page.gPrevious.setValue(true)
    page.gPreviouslyInjected.setValue(true)
    page.hCurrent.setValue('Daily')
    page.hCurrentlyInjected.setValue(true)
    page.hPrevious.setValue(true)
    page.hPreviouslyInjected.setValue(true)
    page.iCurrent.setValue('Weekly')
    page.iPrevious.setValue(true)
    page.jCurrent.setValue('Monthly')
    page.jPrevious.setValue(true)
    page.kCurrent.setValue('Occasional')
    page.kPrevious.setValue(true)
    page.lCurrent.setValue('Daily')
    page.lPrevious.setValue(true)
    page.mCurrent.setValue('Weekly')
    page.mCurrentlyInjected.setValue(true)
    page.mPrevious.setValue(true)
    page.mPreviouslyInjected.setValue(true)
    page.pCurrent.setValue('Monthly')
    page.pPrevious.setValue(true)
    page.nCurrent.setValue('Occasional')
    page.nCurrentlyInjected.setValue(true)
    page.nPrevious.setValue(true)
    page.nPreviouslyInjected.setValue(true)
    page.other.setValue('Some other stuff from time to time')
    page.o8_8.setValue('2-Significant problems')

    page.o9_1.setValue('1-Some problems')
    page.o9_2.setValue('0-No problems')
    page.o11_2.setValue('0-No problems')
    page.o11_4.setValue('1-Some problems')
    page.o12_1.setValue('1-Some problems')
}